execute @s[tag=!levitating,tag=!ground,tag=!dead,tag=!riding,tag=!gliding,m=!c,scores={fly_timer=120..}] ~ ~ ~ detect ~ ~-1 ~ air 0 execute @s ~ ~ ~ detect ~ ~-2 ~ air 0 execute @s ~ ~ ~ detect ~ ~-3 ~ air 0 execute @s ~ ~ ~ detect ~ ~-4 ~ air 0 execute @s ~ ~ ~ detect ~ ~-5 ~ air 0 tp ~ ~-3 ~
execute @s[tag=!levitating,tag=!ground,tag=!dead,tag=!riding,tag=!gliding,m=!c,scores={fly_timer=120..}] ~ ~ ~ detect ~ ~-1 ~ air 0 execute @s ~ ~ ~ detect ~ ~-2 ~ air 0 execute @s ~ ~ ~ detect ~ ~-3 ~ air 0 execute @s ~ ~ ~ detect ~ ~-4 ~ air 0 execute @s ~ ~ ~ detect ~ ~-5 ~ air 0 tp ~ ~-3 ~
execute @s[tag=!levitating,tag=!ground,tag=!dead,tag=!riding,tag=!gliding,m=!c,scores={fly_timer=120..}] ~ ~ ~ detect ~ ~-1 ~ air 0 execute @s ~ ~ ~ detect ~ ~-2 ~ air 0 execute @s ~ ~ ~ detect ~ ~-3 ~ air 0 execute @s ~ ~ ~ detect ~ ~-4 ~ air 0 execute @s ~ ~ ~ detect ~ ~-5 ~ air 0 tp ~ ~-3 ~
execute @s[tag=!levitating,tag=!ground,tag=!dead,tag=!riding,tag=!gliding,m=!c,scores={fly_timer=120..}] ~ ~ ~ detect ~ ~-1 ~ air 0 execute @s ~ ~ ~ detect ~ ~-2 ~ air 0 execute @s ~ ~ ~ detect ~ ~-3 ~ air 0 execute @s ~ ~ ~ detect ~ ~-4 ~ air 0 execute @s ~ ~ ~ detect ~ ~-5 ~ air 0 tp ~ ~-3 ~
execute @s[tag=!levitating,tag=!ground,tag=!dead,tag=!riding,tag=!gliding,m=!c,scores={fly_timer=120..}] ~ ~ ~ detect ~ ~-1 ~ air 0 execute @s ~ ~ ~ detect ~ ~-2 ~ air 0 execute @s ~ ~ ~ detect ~ ~-3 ~ air 0 execute @s ~ ~ ~ detect ~ ~-4 ~ air 0 execute @s ~ ~ ~ detect ~ ~-5 ~ air 0 kill @s[scores={flyvl=10..}]
execute @s[tag=!levitating,tag=!ground,tag=!dead,tag=!riding,tag=!gliding,m=!c,scores={fly_timer=120..}] ~ ~ ~ detect ~ ~-1 ~ air 0 execute @s ~ ~ ~ detect ~ ~-2 ~ air 0 execute @s ~ ~ ~ detect ~ ~-3 ~ air 0 execute @s ~ ~ ~ detect ~ ~-4 ~ air 0 execute @s ~ ~ ~ detect ~ ~-5 ~ air 0 ability @s mayfly false
execute @s[tag=!levitating,tag=!ground,tag=!dead,tag=!riding,tag=!gliding,m=!c,scores={fly_timer=120..}] ~ ~ ~ detect ~ ~-1 ~ air 0 execute @s ~ ~ ~ detect ~ ~-2 ~ air 0 execute @s ~ ~ ~ detect ~ ~-3 ~ air 0 execute @s ~ ~ ~ detect ~ ~-4 ~ air 0 execute @s ~ ~ ~ detect ~ ~-5 ~ air 0 function checks/alerts/fly
execute @s[tag=!levitating,tag=!ground,tag=!dead,tag=!riding,tag=!gliding,m=!c,scores={fly_timer=120..}] ~ ~ ~ detect ~ ~-1 ~ air 0 execute @s ~ ~ ~ detect ~ ~-2 ~ air 0 execute @s ~ ~ ~ detect ~ ~-3 ~ air 0 execute @s ~ ~ ~ detect ~ ~-4 ~ air 0 execute @s ~ ~ ~ detect ~ ~-5 ~ air 0 tp ~ ~-3 ~
execute @s[tag=!levitating,tag=!ground,tag=!dead,tag=!riding,tag=!gliding,m=!c,scores={fly_timer=..120}] ~ ~ ~ detect ~ ~-1 ~ air 0 execute @s ~ ~ ~ detect ~ ~-2 ~ air 0 scoreboard players add @s fly_timer 1
execute @s[m=!c,tag=levitating] ~ ~ ~ scoreboard players set @s fly_timer 0
execute @s[m=!c,tag=gliding] ~ ~ ~ scoreboard players set @s fly_timer 0
execute @s[m=!c,tag=ground] ~ ~ ~ scoreboard players set @s fly_timer 0
execute @s[m=!c,tag=riding] ~ ~ ~ scoreboard players set @s fly_timer 0
execute @s[scores={flyvl=1..}] ~ ~ ~ tag @s add flyFlag