import { EntityInventoryComponent, Player, world } from "@minecraft/server";
import { dynamicPropertyRegistry } from "../../penrose/WorldInitializeAfterEvent/registry.js";
import { sendMsgToPlayer } from "../../util";
import { ActionFormData, ModalFormResponse } from "@minecraft/server-ui";
import { paradoxui } from "../paradoxui.js";

export async function uiINVENTORY(inventoryUIResult: ModalFormResponse, onlineList: string[], player: Player) {
    const [value] = inventoryUIResult.formValues;
    let member: Player = undefined;
    const players = world.getPlayers();
    for (const pl of players) {
        if (pl.name.toLowerCase().includes(onlineList[value as number].toLowerCase().replace(/"|\\|@/g, ""))) {
            member = pl;
            break;
        }
    }
    // Get unique ID
    const uniqueId = dynamicPropertyRegistry.get(player?.id);
    // Make sure the user has permissions to run the command
    if (uniqueId !== player.name) {
        return sendMsgToPlayer(player, `§r§4[§6Paradox§4]§r You need to be Paradox-Opped.`);
    }

    // Are they online?
    if (!member) {
        return sendMsgToPlayer(player, `§r§4[§6Paradox§4]§r Couldnt find that player!`);
    }
    const inv = member.getComponent("inventory") as EntityInventoryComponent;
    const container = inv.container;
    const itemArray: (string | number)[] = [];

    const maxSlots = 36; // Maximum number of slots in the player's inventory

    // Loop through the inventory and add items to the itemArray
    for (let i = 0; i < maxSlots; i++) {
        const item = container.getItem(i);
        if (item?.typeId) {
            itemArray.push(i, item.typeId.replace("minecraft:", ""), item.amount, item.typeId.replace("minecraft:", ""));
        } else {
            itemArray.push(i, "empty", 0, "ui/slots_bg");
        }
    }

    // Map of all items/blocks and their texture paths
    const textures = new Map([
        //default texture if the slot is empty or no texture is found in the map
        ["empty", "ui/slots_bg"],
        //blocks
        ["acacia_button", "blocks/planks_acacia"],
        ["acacia_door", "blocks/door_acacia_upper"],
        ["acacia_fence", "blocks/planks_acacia"],
        ["acacia_fence_gate", "blocks/planks_acacia"],
        ["acacia_hanging_sign", "blocks/acacia_hanging_sign"],
        ["acacia_log", "blocks/log_acacia"],
        ["acacia_pressure_plate", "blocks/planks_acacia"],
        ["acacia_stairs", "blocks/planks_acacia"],
        ["acacia_standing_sign", "items/sign_acacia"],
        ["acacia_trapdoor", "blocks/acacia_trapdoor"],
        ["acacia_wall_sign", "items/sign_acacia"],
        ["activator_rail", "blocks/rail_activator"],
        ["air", ""],
        ["allow", "blocks/build_allow"],
        ["amethyst_block", "blocks/amethyst_block"],
        ["amethyst_cluster", "blocks/amethyst_cluster"],
        ["ancient_debris", "blocks/ancient_debris_side"],
        ["andesite_stairs", "blocks/stone_andesite"],
        ["anvil", "blocks/anvil_top_damaged_0"],
        ["azalea", "blocks/azalea_side"],
        ["azalea_leaves", "blocks/azalea_leaves"],
        ["azalea_leaves_flowered", "blocks/azalea_leaves_flowers"],
        ["bamboo", "blocks/bamboo"],
        ["bamboo_block", "blocks/bamboo_block"],
        ["bamboo_button", "blocks/bamboo"],
        ["bamboo_door", "blocks/bamboo_door"],
        ["bamboo_double_slab", "blocks/bamboo"],
        ["bamboo_fence", "blocks/bamboo_fence"],
        ["bamboo_fence_gate", "blocks/bamboo_fence_gate"],
        ["bamboo_hanging_sign", "blocks/bamboo_hanging_sign"],
        ["bamboo_mosaic", "blocks/bamboo_mosaic"],
        ["bamboo_mosaic_double_slab", "blocks/bamboo_mosaic"],
        ["bamboo_mosaic_slab", "blocks/bamboo_mosaic"],
        ["bamboo_mosaic_stairs", "blocks/bamboo_mosaic"],
        ["bamboo_planks", "blocks/bamboo_planks"],
        ["bamboo_pressure_plate", "blocks/bamboo_plank"],
        ["bamboo_sapling", "blocks/bamboo_sapling"],
        ["bamboo_slab", "blocks/bamboo_plank"],
        ["bamboo_stairs", "blocks/bamboo_plank"],
        ["bamboo_standing_sign", "items/bamboo_sign"],
        ["bamboo_trapdoor", "blocks/bamboo_trapdoor"],
        ["bamboo_wall_sign", "items/bamboo_sign"],
        ["barrel", "blocks/barrel_side"],
        ["barrier", "blocks/barrier"],
        ["basalt", "blocks/basalt_side"],
        ["beacon", "blocks/beacon"],
        ["bed", "items/bed_red"],
        ["bedrock", "blocks/bedrock"],
        ["bee_nest", "blocks/bee_nest_side"],
        ["beehive", "blocks/beehive_side"],
        ["beetroot", "blocks/beetroot"],
        ["bell", "blocks/beehive_side"],
        ["big_dripleaf", "blocks/big_dripleaf_side1"],
        ["birch_button", "blocks/planks_birch"],
        ["birch_door", "blocks/door_birch_upper"],
        ["birch_fence", "blocks/planks_birch"],
        ["birch_fence_gate", "blocks/planks_birch"],
        ["birch_hanging_sign", "blocks/birch_hanging_sign"],
        ["birch_log", "log_birch"],
        ["birch_pressure_plate", "blocks/planks_birch"],
        ["birch_stairs", "blocks/planks_birch"],
        ["birch_standing_sign", "items/sign_birch"],
        ["birch_trapdoor", "blocks/birch_trapdoor"],
        ["birch_wall_sign", "items/sign_birch"],
        ["black_candle", "blocks/candles/black_candle"],
        ["black_candle_cake", "blocks/candles/black_candle"],
        ["black_carpet", "blocks/wool_colored_black"],
        ["black_concrete", "blocks/concrete_black"],
        ["black_glazed_terracotta", "blocks/glazed_terracotta_black"],
        ["black_shulker_box", "blocks/shulker_top_black"],
        ["black_wool", "blocks/wool_colored_black"],
        ["blackstone", "blocks/blackstone"],
        ["blackstone_double_slab", "blocks/blackstone"],
        ["blackstone_slab", "blocks/blackstone"],
        ["blackstone_stairs", "blocks/blackstone"],
        ["blackstone_wall", "blocks/blackstone"],
        ["blast_furnace", "blocks/blast_furnace_front_off"],
        ["blue_candle", "blocks/candles/blue_candle"],
        ["blue_candle_cake", "blocks/candles/blue_candle"],
        ["blue_carpet", "blocks/wool_colored_blue"],
        ["blue_concrete", "blocks/concrete_blue"],
        ["blue_glazed_terracotta", "blocks/glazed_terracotta_blue"],
        ["blue_ice", "blocks/blue_ice"],
        ["blue_shulker_box", "blocks/shulker_top_blue"],
        ["blue_wool", "blocks/wool_colored_blue"],
        ["bone_block", "blocks/bone_block_side"],
        ["bookshelf", "blocks/bookshelf"],
        ["border_block", "blocks/border"],
        ["brain_coral", "blocks/coral_fan_pink"],
        ["brewing_stand", "blocks/brewing_stand"],
        ["brick_block", "blocks/brick"],
        ["brick_stairs", "blocks/brick"],
        ["brown_candle", "blocks/candles/brown_candle"],
        ["brown_candle_cake", "blocks/candles/brown_candle"],
        ["brown_carpet", "blocks/wool_colored_brown"],
        ["brown_concrete", "blocks/concrete_brown"],
        ["brown_glazed_terracotta", "blocks/glazed_terracotta_brown"],
        ["brown_mushroom", "blocks/mushroom_brown"],
        ["brown_mushroom_block", "blocks/mushroom_brown"],
        ["brown_shulker_box", "blocks/shulker_top_brown"],
        ["brown_wool", "blocks/wool_colored_brown"],
        ["bubble_column", "blocks/bubble_column_down_top_a"],
        ["bubble_coral", "blocks/coral_fan_pink"],
        ["budding_amethyst", "blocks/budding_amethyst"],
        ["cactus", "blocks/cactus_side"],
        ["cake", "blocks/cake"],
        ["calcite", "blocks/calcite"],
        ["calibrated_sculk_sensor", "blocks/calibrated_sculk_sensor_input_side"],
        ["camera", "blocks/camera_side"],
        ["campfire", "blocks/campfire"],
        ["candle", "blocks/candle"],
        ["candle_cake", "blocks/candle"],
        ["carrots", "items/carrot"],
        ["cartography_table", "blocks/cartography_table_side2"],
        ["carved_pumpkin", "blocks/pumpkin_face_off"],
        ["cauldron", "blocks/cauldron"],
        ["cave_vines", "blocks/cave_vines_body"],
        ["cave_vines_body_with_berries", "blocks/cave_vines_body_berries"],
        ["cave_vines_head_with_berries", "blocks/cave_vines_head_berries"],
        ["chain", "blocks/chain"],
        ["chain_command_block", "blocks/chain_command_block_side_mipmap"],
        ["chemical_heat", ""],
        ["chemistry_table", ""],
        ["cherry_button", "blocks/cherry_planks"],
        ["cherry_door", "blocks/cherry_door"],
        ["cherry_double_slab", "blocks/cherry_planks"],
        ["cherry_fence", "blocks/cherry_planks"],
        ["cherry_fence_gate", "blocks/cherry_planks"],
        ["cherry_hanging_sign", "blocks/cherry_hanging_sign"],
        ["cherry_leaves", "blocks/cherry_leaves"],
        ["cherry_log", "blocks/cherry_log_side"],
        ["cherry_planks", "blocks/cherry_planks"],
        ["cherry_pressure_plate", "blocks/cherry_planks"],
        ["cherry_sapling", "blocks/cherry_sapling"],
        ["cherry_slab", "blocks/cherry_planks"],
        ["cherry_stairs", "blocks/cherry_planks"],
        ["cherry_standing_sign", "items/cherry_sign"],
        ["cherry_trapdoor", "blocks/cherry_trapdoor"],
        ["cherry_wall_sign", "items/cherry_sign"],
        ["cherry_wood", "blocks/cherry_log_top"],
        ["chest", "blocks/chest_front"],
        ["chiseled_bookshelf", "blocks/chiseled_bookshelf_side"],
        ["chiseled_deepslate", "blocks/deepslate/chiseled_deepslate"],
        ["chiseled_nether_bricks", "blocks/chiseled_nether_bricks"],
        ["chiseled_polished_blackstone", "blocks/chiseled_polished_blackstone"],
        ["chorus_flower", "blocks/chorus_flower"],
        ["chorus_plant", "blocks/chorus_plant"],
        ["clay", "blocks/clay"],
        ["client_request_placeholder_block", ""],
        ["coal_block", "blocks/coal_block"],
        ["coal_ore", "blocks/coal_ore"],
        ["cobbled_deepslate", "blocks/deepslate/cobbled_deepslate"],
        ["cobbled_deepslate_double_slab", "blocks/deepslate/cobbled_deepslate"],
        ["cobbled_deepslate_slab", "blocks/deepslate/cobbled_deepslate"],
        ["cobbled_deepslate_stairs", "blocks/deepslate/cobbled_deepslate"],
        ["cobbled_deepslate_wall", "blocks/deepslate/cobbled_deepslate"],
        ["cobblestone", "blocks/cobblestone"],
        ["cobblestone_wall", "blocks/cobblestone"],
        ["cocoa", "blocks/cocoa_stage_2"],
        ["colored_torch_bp", ""],
        ["colored_torch_rg", ""],
        ["command_block", "blocks/command_block"],
        ["composter", "blocks/composter_side"],
        ["concrete_powder", "blocks/concrete_powder_gray"],
        ["conduit", "blocks/conduit_open"],
        ["copper_block", "blocks/copper_block"],
        ["copper_ore", "blocks/copper_ore"],
        ["coral_block", "blocks/coral_blue"],
        ["coral_fan", "blocks/coral_fan_blue"],
        ["coral_fan_dead", "blocks/coral_fan_blue_dead"],
        ["coral_fan_hang", "blocks/coral_fan_blue"],
        ["coral_fan_hang2", "blocks/coral_fan_pink"],
        ["coral_fan_hang3", "blocks/coral_fan_yellow"],
        ["cracked_deepslate_bricks", "blocks/deepslate/cracked_deepslate_bricks"],
        ["cracked_deepslate_tiles", "blocks/deepslate/cracked_deepslate_tiles"],
        ["cracked_nether_bricks", "blocks/cracked_nether_bricks"],
        ["cracked_polished_blackstone_bricks", "blocks/cracked_polished_blackstone_bricks"],
        ["crafting_table", "blocks/crafting_table_front"],
        ["crimson_button", "blocks/huge_fungus/crimson_planks"],
        ["crimson_door", "items/crimson_door"],
        ["crimson_double_slab", "blocks/huge_fungus/crimson_planks"],
        ["crimson_fence", "blocks/huge_fungus/crimson_planks"],
        ["crimson_fence_gate", "blocks/huge_fungus/crimson_planks"],
        ["crimson_fungus", "blocks/crimson_fungus"],
        ["crimson_hanging_sign", "items/crimson_hanging_sign"],
        ["crimson_hyphae", "blocks/huge_fungus/crimson_log_side"],
        ["crimson_nylium", "blocks/crimson_nylium_side"],
        ["crimson_planks", "blocks/huge_fungus/crimson_planks"],
        ["crimson_pressure_plate", "blocks/huge_fungus/crimson_planks"],
        ["crimson_roots", "blocks/crimson_roots"],
        ["crimson_slab", "blocks/huge_fungus/crimson_planks"],
        ["crimson_stairs", "blocks/huge_fungus/crimson_planks"],
        ["crimson_standing_sign", "items/sign_crimson"],
        ["crimson_stem", "blocks/huge_fungus/crimson_log_side"],
        ["crimson_trapdoor", "blocks/crimson_trapdoor"],
        ["crimson_wall_sign", "items/sign_crimson"],
        ["crying_obsidian", "blocks/crying_obsidian"],
        ["cut_copper", "blocks/cut_copper"],
        ["cut_copper_slab", "blocks/cut_copper"],
        ["cut_copper_stairs", "blocks/cut_copper"],
        ["cyan_candle", "blocks/cyan_candle"],
        ["cyan_candle_cake", "blocks/candles/cyan_candle"],
        ["cyan_carpet", "blocks/wool_colored_cyan"],
        ["cyan_concrete", "blocks/concrete_cyan"],
        ["cyan_glazed_terracotta", "blocks/glazed_terracotta_cyan"],
        ["cyan_shulker_box", "blocks/shulker_top_cyan"],
        ["cyan_wool", "blocks/wool_colored_cyan"],
        ["dark_oak_button", "blocks/planks_big_oak"],
        ["dark_oak_door", "items/door_dark_oak"],
        ["dark_oak_fence", "blocks/planks_big_oak"],
        ["dark_oak_fence_gate", "blocks/planks_big_oak"],
        ["dark_oak_hanging_sign", "items/dark_oak_hanging_sign"],
        ["dark_oak_log", "blocks/log_big_oak"],
        ["dark_oak_pressure_plate", "blocks/planks_big_oak"],
        ["dark_oak_stairs", "blocks/planks_big_oak"],
        ["dark_oak_trapdoor", "blocks/dark_oak_trapdoor"],
        ["dark_prismarine_stairs", "blocks/prismarine_dark"],
        ["darkoak_standing_sign", "items/sign_darkoak"],
        ["darkoak_wall_sign", "items/sign_darkoak"],
        ["daylight_detector", "blocks/daylight_detector_top"],
        ["daylight_detector_inverted", "blocks/daylight_detector_inverted_top"],
        ["dead_brain_coral", "blocks/coral_plant_purple_dead"],
        ["dead_bubble_coral", "blocks/coral_plant_pink_dead"],
        ["dead_fire_coral", "blocks/coral_plant_red_dead"],
        ["dead_horn_coral", "blocks/coral_plant_yellow_dead"],
        ["dead_tube_coral", "blocks/coral_plant_blue_dead"],
        ["deadbush", "blocks/deadbush"],
        ["decorated_pot", "blocks/decorated_pot_side"],
        ["deepslate", "blocks/deepslate/deepslate"],
        ["deepslate_brick_double_slab", "blocks/deepslate/deepslate_bricks"],
        ["deepslate_brick_slab", "blocks/deepslate/deepslate_bricks"],
        ["deepslate_brick_stairs", "blocks/deepslate/deepslate_bricks"],
        ["deepslate_brick_wall", "blocks/deepslate/deepslate_bricks"],
        ["deepslate_bricks", "blocks/deepslate/deepslate_bricks"],
        ["deepslate_coal_ore", "blocks/deepslate/deepslate_coal_ore"],
        ["deepslate_copper_ore", "blocks/deepslate/deepslate_copper_ore"],
        ["deepslate_diamond_ore", "blocks/deepslate/deepslate_diamond_ore"],
        ["deepslate_emerald_ore", "blocks/deepsalte/deepslate_emerald_ore"],
        ["deepslate_gold_ore", "blocks/deepslate/deepslate_gold_ore"],
        ["deepslate_iron_ore", "blocks/deepslate/deepslate_iron_ore"],
        ["deepslate_lapis_ore", "blocks/deepslate/deepslate_lapis_ore"],
        ["deepslate_redstone_ore", "blocks/deepslate/deepslate_redstone_ore"],
        ["deepslate_tile_double_slab", "blocks/deepslate/deepslate_tiles"],
        ["deepslate_tile_slab", "blocks/deepslate/deepslate_tiles"],
        ["deepslate_tile_stairs", "blocks/deepslate/deepslate_tiles"],
        ["deepslate_tile_wall", "blocks/deepslate/deepslate_tiles"],
        ["deepslate_tiles", "blocks/deepslate/deepslate_tiles"],
        ["deny", "blocks/build_deny"],
        ["detector_rail", "blocks/rail_detector"],
        ["diamond_block", "blocks/diamond_block"],
        ["diamond_ore", "blocks/diamond_ore"],
        ["diorite_stairs", "blocks/stone_diorite"],
        ["dirt", "blocks/dirt"],
        ["dirt_with_roots", "blocks/dirt_with_roots"],
        ["dispenser", "blocks/dispenser_front_horizontal"],
        ["double_cut_copper_slab", "blocks/cut_copper"],
        ["double_plant", "blocks/double_plant_fern_carried"],
        ["double_stone_block_slab", "blocks/stone_slab_side"],
        ["double_stone_block_slab2", "blocks/red_sandstone_bottom"],
        ["double_stone_block_slab3", "blocks/end_bricks"],
        ["double_stone_block_slab4", "blocks/stonebrick"],
        ["double_wooden_slab", "blocks/planks_oak"],
        ["dragon_egg", "blocks/dragon_egg"],
        ["dried_kelp_block", "blocks/dried_kelp_top"],
        ["dripstone_block", "blocks/dripstone_block"],
        ["dropper", "blocks/dropper_front_horizontal"],
        ["emerald_block", "blocks/emerald_block"],
        ["emerald_ore", "blocks/emerald_ore"],
        ["enchanting_table", "blocks/enchanting_table_side"],
        ["end_brick_stairs", "blocks/end_bricks"],
        ["end_bricks", "blocks/end_bricks"],
        ["end_gateway", "blocks/end_gateway"],
        ["end_portal", "blocks/end_portal"],
        ["end_portal_frame", "blocks/endframe_top"],
        ["end_rod", "blocks/end_rod"],
        ["end_stone", "blocks/end_stone"],
        ["ender_chest", "blocks/ender_chest_front"],
        ["exposed_copper", "blocks/exposed_copper"],
        ["exposed_cut_copper", "blocks/exposed_cut_copper"],
        ["exposed_cut_copper_slab", "blocks/exposed_cut_copper"],
        ["exposed_cut_copper_stairs", "blocks/exposed_cut_copper"],
        ["exposed_double_cut_copper_slab", "blocks/cut_copper"],
        ["farmland", "blocks/farmland_dry"],
        ["fence_gate", "blocks/planks_oak"],
        ["fire", "blocks/fire_1_placeholder"],
        ["fire_coral", "blocks/coral_fan_red"],
        ["fletching_table", "blocks/fletcher_table_side1"],
        ["flower_pot", "blocks/flower_pot"],
        ["flowering_azalea", "blocks/flowering_azalea_side"],
        ["flowing_lava", "blocks/lava_placeholder"],
        ["flowing_water", "blocks/water_placeholder"],
        ["frame", "blocks/itemframe_background"],
        ["frog_spawn", "blocks/frogspawn"],
        ["frosted_ice", ""],
        ["furnace", ""],
        ["gilded_blackstone", "blocks/gilded_blackstone"],
        ["glass", "blocks/glass"],
        ["glass_pane", ""],
        ["glow_frame", ""],
        ["glow_lichen", "blocks/glow_lichen"],
        ["glowingobsidian", ""],
        ["glowstone", "blocks/glowstone"],
        ["gold_block", "blocks/gold_block"],
        ["gold_ore", "blocks/gold_ore"],
        ["golden_rail", ""],
        ["granite_stairs", ""],
        ["grass", ""],
        ["grass_path", ""],
        ["gravel", "blocks/gravel"],
        ["gray_candle", "blocks/gray_candle"],
        ["gray_candle_cake", ""],
        ["gray_carpet", ""],
        ["gray_concrete", ""],
        ["gray_glazed_terracotta", ""],
        ["gray_shulker_box", ""],
        ["gray_wool", ""],
        ["green_candle", "blocks/green_candle"],
        ["green_candle_cake", ""],
        ["green_carpet", ""],
        ["green_concrete", ""],
        ["green_glazed_terracotta", ""],
        ["green_shulker_box", ""],
        ["green_wool", ""],
        ["grindstone", ""],
        ["hanging_roots", "blocks/hanging_roots"],
        ["hard_glass", ""],
        ["hard_glass_pane", ""],
        ["hard_stained_glass", ""],
        ["hard_stained_glass_pane", ""],
        ["hardened_clay", "blocks/hardened_clay"],
        ["hay_block", ""],
        ["heavy_weighted_pressure_plate", ""],
        ["honey_block", ""],
        ["honeycomb_block", ""],
        ["hopper", "blocks/hopper"],
        ["horn_coral", ""],
        ["ice", "blocks/ice"],
        ["infested_deepslate", "blocks/deepslate/deepslate"],
        ["info_update", ""],
        ["info_update2", ""],
        ["invisible_bedrock", ""],
        ["iron_bars", "blocks/iron_bars"],
        ["iron_block", "blocks/iron_block"],
        ["iron_door", ""],
        ["iron_ore", "blocks/iron_ore"],
        ["iron_trapdoor", "blocks/iron_trapdoor"],
        ["jigsaw", ""],
        ["jukebox", ""],

        //items
        ["acacia_door", "items/door_acacia"],
        ["amethyst_shard", "items/amethyst_shard"],
        ["apple", "items/apple"],
        ["apple_golden", "items/apple_golden"],
        ["armor_stand", "items/armor_stand"],
        ["arrow", "items/arrow"],
        ["wooden_axe", "items/wood_axe"],
        ["stone_axe", "items/stone_axe"],
        ["iron_axe", "items/iron_axe"],
        ["golden_axe", "items/gold_axe"],
        ["diamond_axe", "items/diamond_axe"],
        ["netherite_axe", "items/netherite_axe"],
        ["banner_pattern", "items/banner_pattern"],
        ["bed", "items/bed_red"],
        ["beef_cooked", "items/beef_cooked"],
        ["beef_raw", "items/beef_raw"],
        ["beetroot", "items/beetroot"],
        ["beetroot_soup", "items/beetroot_soup"],
        ["birch_door", "items/door_birch"],
        ["blaze_powder", "items/blaze_powder"],
        ["blaze_rod", "items/blaze_rod"],
        ["oak_boat", "items/boat_oak"],
        ["spruce_boat", "items/boat_spruce"],
        ["birch_boat", "items/boat_birch"],
        ["jungle_boat", "items/boat_jungle"],
        ["acacia_boat", "items/boat_acacia"],
        ["dark_boat", "items/boat_darkoak"],
        ["mangrove_boat", "items/mangrove_boat"],
        ["cherry_boat", "items/cherry_boat"],
        ["bamboo_raft", "items/bamboo_raft"],
        ["bone", "items/bone"],
        ["book_enchanted", "items/book_enchanted"],
        ["book_normal", "items/book_normal"],
        ["book_portfolio", "items/book_portfolio"],
        ["book_writable", "items/book_writable"],
        ["book_written", "items/book_written"],
        ["leather_helmet", "items/leather_helmet"],
        ["chainmail_helmet", "items/chainmail_helmet"],
        ["iron_helmet", "items/iron_helmet"],
        ["golden_helmet", "items/gold_helmet"],
        ["diamond_helmet", "items/diamond_helmet"],
        ["netherite_helmet", "items/netherite_helmet"],
        ["leather_chestplate", "items/leather_chestplate"],
        ["chainmail_chestplate", "items/chainmail_chestplate"],
        ["iron_chestplate", "items/iron_chestplate"],
        ["golden_chestplate", "items/gold_chestplate"],
        ["diamond_chestplate", "items/diamond_chestplate"],
        ["netherite_chestplate", "items/netherite_chestplate"],
        ["leather_leggings", "items/leather_leggings"],
        ["chainmail_leggings", "items/chainmail_leggings"],
        ["iron_leggings", "items/iron_leggings"],
        ["golden_leggings", "items/gold_leggings"],
        ["diamond_leggings", "items/diamond_leggings"],
        ["netherite", "items/netherite_leggings"],
        ["leather_boots", "items/leather_boots"],
        ["chainmail_boots", "items/chainmail_boots"],
        ["iron_boots", "items/iron_boots"],
        ["golden_boots", "items/gold_boots"],
        ["diamond_boots", "items/diamond_boots"],
        ["netherite_boots", "items/netherite_boots"],
        ["bow", "bow_standby"],
        ["bowl", "items/bowl"],
        ["bread", "items/bread"],
        ["brewing_stand", "items/brewing_stand"],
        ["brick", "items/brick"],
        ["bucket", "items/bucket_empty"],
        ["milk_bucket", "items/bucket_milk"],
        ["water_bucket", "items/bucket_water"],
        ["lava_bucket", "items/bucket_lava"],
        ["cod_bucket", "items/bucket_cod"],
        ["salmon_bucket", "items/bucket_salmon"],
        ["tropical_bucket", "items/bucket_tropical"],
        ["pufferfish_bucket", "items/bucket_pufferfish"],
        ["powder_snow_bucket", "items/bucket_powder_snow"],
        ["axolotl_bucket", "items/bucket_axolotl"],
        ["tadpole_bucket", "items/bucket_tadpole"],
        ["oak_chest_boat", "items/oak_chest_boat"],
        ["spruce_chest_boat", "items/spruce_chest_boat"],
        ["birch_chest_boat", "items/birch_chest_boat"],
        ["jungle_chest_boat", "items/jungle_chest_boat"],
        ["acacia_chest_boat", "items/acacia_chest_boat"],
        ["dark_oak_chest_boat", "items/dark_oak_chest_boat"],
        ["mangrove_chest_boat", "items/mangrove_chest_boat"],
        ["cherry_chest_boat", "items/cherry_chest_boat"],
        ["bamboo_chest_raft", "items/bamboo_chest_raft"],

        // Add more mappings for other items/blocks
    ]);

    // Update the fourth value (texture) in the itemArray
    for (let i = 0; i < itemArray.length; i += 4) {
        const type: string | number = itemArray[i + 3];
        const texture: string = textures.get(type.toString()) || "ui/slots_bg";
        itemArray[i + 3] = texture;
    }

    // Output the updated itemArray
    console.log(itemArray);

    //once the loop is done then move to the next part

    const playerInventory = new ActionFormData();
    playerInventory.title("§4" + member.nameTag + " Inventory" + "§4");
    playerInventory.button(itemArray[1] + " Amount: " + itemArray[2], "textures/" + itemArray[3]);
    playerInventory.button(itemArray[5] + " Amount: " + itemArray[6], "textures/" + itemArray[7]);
    playerInventory.button(itemArray[9] + " Amount: " + itemArray[10], "textures/" + itemArray[11]);
    playerInventory.button(itemArray[13] + " Amount: " + itemArray[14], "textures/" + itemArray[15]);
    playerInventory.show(player).then((playerInventoryResult) => {
        if (playerInventoryResult.selection === 4) {
            return paradoxui(player);
        }
        return paradoxui(player);
    });
}
