// verses.js
export const verses = [
    // Old Testament
    "Genesis 1:1 — In the beginning, God created the heavens and the earth.",
    "Exodus 14:14 — The Lord will fight for you; you need only to be still.",
    "Psalm 23:1 — The Lord is my shepherd; I shall not want.",
    "Psalm 46:1 — God is our refuge and strength, a very present help in trouble.",
    "Psalm 118:24 — This is the day that the Lord has made; let us rejoice and be glad in it.",
    "Proverbs 3:5 — Trust in the Lord with all your heart.",
    "Isaiah 41:10 — Fear not, for I am with you.",
    "Isaiah 40:31 — But they who wait for the Lord shall renew their strength.",
    "Jeremiah 29:11 — For I know the plans I have for you.",
    "Lamentations 3:22 — The steadfast love of the Lord never ceases.",
    "Micah 6:8 — Walk humbly with your God.",
    "Nahum 1:7 — The Lord is good, a stronghold in the day of trouble.",
    "Zephaniah 3:17 — The Lord your God is in your midst.",
    "Hosea 6:6 — For I desire steadfast love, not sacrifice.",
    "Joel 2:28 — I will pour out my Spirit on all flesh.",
    "Amos 5:24 — Let justice roll down like waters.",
    "Obadiah 1:15 — The day of the Lord is near for all nations.",
    "Jonah 2:2 — I called out to the Lord, and he answered me.",
    "Habakkuk 3:19 — The Lord God is my strength.",
    "Malachi 3:10 — Bring the full tithe into the storehouse.",
    "1 Samuel 16:7 — The Lord sees not as man sees.",
    "2 Samuel 22:31 — The Word of the Lord is proven.",
    "1 Kings 8:56 — Blessed be the Lord who has given rest.",
    "2 Kings 20:5 — I have heard your prayer.",
    "Ezra 10:4 — Arise, for it is your task.",
    "Genesis 50:20 — You meant evil against me, but God meant it for good.",
    "Exodus 33:14 — My presence will go with you, and I will give you rest.",
    "Numbers 6:24 — The Lord bless you and keep you.",
    "Deuteronomy 31:8 — The Lord himself goes before you and will be with you.",
    "Joshua 1:9 — Be strong and courageous. Do not be frightened.",
    "Judges 5:31 — Let those who love him be like the sun.",
    "Ruth 2:12 — May the Lord repay you for what you have done.",
    "1 Samuel 12:24 — Fear the Lord and serve him faithfully.",
    "2 Samuel 22:2 — The Lord is my rock and my fortress.",
    "1 Chronicles 16:11 — Seek the Lord and his strength.",
    "2 Chronicles 16:9 — The eyes of the Lord range throughout the earth.",
    "Nehemiah 8:10 — The joy of the Lord is your strength.",
    "Job 19:25 — I know that my Redeemer lives.",
    "Psalm 27:1 — The Lord is my light and my salvation.",
    "Psalm 55:22 — Cast your burden on the Lord.",
    "Psalm 119:11 — I have stored up your word in my heart.",
    "Proverbs 16:3 — Commit your work to the Lord.",
    "Ecclesiastes 3:11 — He has made everything beautiful in its time.",
    "Song of Solomon 8:7 — Many waters cannot quench love.",
    "Isaiah 26:3 — You keep him in perfect peace whose mind is stayed on you.",
    "Isaiah 43:2 — When you pass through the waters, I will be with you.",
    "Jeremiah 33:3 — Call to me and I will answer you.",
    "Ezekiel 36:26 — I will give you a new heart.",
    "Daniel 6:23 — No harm was found on him because he trusted in his God.",
    "Zechariah 4:6 — Not by might, nor by power, but by my Spirit.",

    // New Testament
    "John 3:16 — For God so loved the world...",
    "Romans 8:28 — All things work together for good.",
    "1 Corinthians 13:4 — Love is patient and kind...",
    "Philippians 4:13 — I can do all things through Christ...",
    "2 Corinthians 5:7 — We walk by faith, not by sight.",
    "Galatians 5:22 — The fruit of the Spirit is love, joy, peace...",
    "Ephesians 2:8 — By grace you have been saved through faith.",
    "Colossians 3:23 — Whatever you do, work heartily.",
    "1 Thessalonians 5:16 — Rejoice always.",
    "2 Thessalonians 3:3 — The Lord is faithful.",
    "1 Timothy 4:12 — Set the believers an example.",
    "2 Timothy 1:7 — For God gave us a spirit not of fear.",
    "Titus 2:11 — For the grace of God has appeared.",
    "Philemon 1:7 — Your love has refreshed the hearts of the saints.",
    "Hebrews 11:1 — Now faith is the assurance of things hoped for.",
    "Hebrews 13:5 — I will never leave you nor forsake you.",
    "James 1:5 — If any lacks wisdom, let him ask God.",
    "1 Peter 5:7 — Cast all your anxieties on him.",
    "2 Peter 3:9 — The Lord is patient toward you.",
    "1 John 4:18 — Perfect love casts out fear.",
    "2 John 1:6 — Walk in love.",
    "3 John 1:2 — I pray that all may go well with you.",
    "Jude 1:24 — To him who is able to keep you from falling.",
    "Revelation 3:20 — Behold, I stand at the door and knock.",
    "Revelation 21:4 — He will wipe away every tear from their eyes.",
    "Matthew 5:14 — You are the light of the world.",
    "Matthew 6:33 — Seek first the kingdom of God.",
    "Matthew 11:28 — Come to me, all who labor and are heavy laden.",
    "Mark 9:23 — All things are possible for one who believes.",
    "Luke 1:37 — Nothing will be impossible with God.",
    "Luke 6:36 — Be merciful, even as your Father is merciful.",
    "John 14:27 — Peace I leave with you; my peace I give to you.",
    "John 15:13 — Greater love has no one than this.",
    "Acts 4:12 — There is salvation in no one else.",
    "Romans 5:8 — God shows his love for us in that while we were sinners, Christ died for us.",
    "Romans 12:12 — Rejoice in hope, be patient in tribulation.",
    "1 Corinthians 16:14 — Let all that you do be done in love.",
    "2 Corinthians 9:7 — God loves a cheerful giver.",
    "Galatians 6:9 — Let us not grow weary of doing good.",
    "Ephesians 3:20 — Now to him who is able to do far more abundantly.",
    "Philippians 2:3 — In humility count others more significant than yourselves.",
    "Colossians 3:15 — Let the peace of Christ rule in your hearts.",
    "1 Thessalonians 5:24 — He who calls you is faithful; he will surely do it.",
    "2 Timothy 2:13 — If we are faithless, he remains faithful.",
    "Hebrews 10:23 — Let us hold fast the confession of our hope.",
    "James 4:8 — Draw near to God, and he will draw near to you.",
    "1 Peter 2:9 — You are a chosen race, a royal priesthood.",
    "2 Peter 1:3 — His divine power has granted to us all things.",
    "1 John 1:9 — If we confess our sins, he is faithful and just to forgive us.",
    "1 John 5:14 — If we ask anything according to his will, he hears us.",
];
