// verses.js
export const verses = [
    // Old Testament (25)
    "Genesis 1:1 — In the beginning, God created the heavens and the earth.",
    "Exodus 14:14 — The Lord will fight for you; you need only to be still.",
    "Psalm 23:1 — The Lord is my shepherd; I shall not want.",
    "Psalm 46:1 — God is our refuge and strength, a very present help in trouble.",
    "Psalm 118:24 — This is the day that the Lord has made; let us rejoice and be glad in it.",
    "Proverbs 3:5 — Trust in the Lord with all your heart.",
    "Isaiah 41:10 — Fear not, for I am with you.",
    "Isaiah 40:31 — But they who wait for the Lord shall renew their strength.",
    "Jeremiah 29:11 — For I know the plans I have for you.",
    "Lamentations 3:22 — The steadfast love of the Lord never ceases.",
    "Micah 6:8 — Walk humbly with your God.",
    "Nahum 1:7 — The Lord is good, a stronghold in the day of trouble.",
    "Zephaniah 3:17 — The Lord your God is in your midst.",
    "Hosea 6:6 — For I desire steadfast love, not sacrifice.",
    "Joel 2:28 — I will pour out my Spirit on all flesh.",
    "Amos 5:24 — Let justice roll down like waters.",
    "Obadiah 1:15 — The day of the Lord is near for all nations.",
    "Jonah 2:2 — I called out to the Lord, and he answered me.",
    "Habakkuk 3:19 — The Lord God is my strength.",
    "Malachi 3:10 — Bring the full tithe into the storehouse.",
    "1 Samuel 16:7 — The Lord sees not as man sees.",
    "2 Samuel 22:31 — The Word of the Lord is proven.",
    "1 Kings 8:56 — Blessed be the Lord who has given rest.",
    "2 Kings 20:5 — I have heard your prayer.",
    "Ezra 10:4 — Arise, for it is your task.",

    // New Testament (25)
    "John 3:16 — For God so loved the world...",
    "Romans 8:28 — All things work together for good.",
    "1 Corinthians 13:4 — Love is patient and kind...",
    "Philippians 4:13 — I can do all things through Christ...",
    "2 Corinthians 5:7 — We walk by faith, not by sight.",
    "Galatians 5:22 — The fruit of the Spirit is love, joy, peace...",
    "Ephesians 2:8 — By grace you have been saved through faith.",
    "Colossians 3:23 — Whatever you do, work heartily.",
    "1 Thessalonians 5:16 — Rejoice always.",
    "2 Thessalonians 3:3 — The Lord is faithful.",
    "1 Timothy 4:12 — Set the believers an example.",
    "2 Timothy 1:7 — For God gave us a spirit not of fear.",
    "Titus 2:11 — For the grace of God has appeared.",
    "Philemon 1:7 — Your love has refreshed the hearts of the saints.",
    "Hebrews 11:1 — Now faith is the assurance of things hoped for.",
    "Hebrews 13:5 — I will never leave you nor forsake you.",
    "James 1:5 — If any lacks wisdom, let him ask God.",
    "1 Peter 5:7 — Cast all your anxieties on him.",
    "2 Peter 3:9 — The Lord is patient toward you.",
    "1 John 4:18 — Perfect love casts out fear.",
    "2 John 1:6 — Walk in love.",
    "3 John 1:2 — I pray that all may go well with you.",
    "Jude 1:24 — To him who is able to keep you from falling.",
    "Revelation 3:20 — Behold, I stand at the door and knock.",
    "Revelation 21:4 — He will wipe away every tear from their eyes.",
];
