import { system, world } from "@minecraft/server";

/** Maximum character length stored per dynamic property chunk */
const CHUNK_SIZE = 30000;

/** Iteration yield threshold to prevent Watchdog timeouts during heavy tasks */
const COMPRESSION_YIELD_THRESHOLD = 5000;

/** Size of batch operations processed during parallelized cleanup sweeps */
const CLEANUP_BATCH_SIZE = 25;

/** Valid structure constraint for database entry values */
export type DatabaseValueObject = Record<string, any>;

/**
 * UTF-16 safe LZW compression utility optimized for Minecraft Script API Dynamic Properties.
 */
class LZCompressor {
    /**
     * Compresses input string asynchronously to yield execution to the server loop.
     * @param uncompressed Uncompressed UTF-8/UTF-16 payload string.
     * @returns Promise resolving to JSON serialized array of dictionary code pointers.
     */
    public static async compress(uncompressed: string): Promise<string> {
        if (!uncompressed) return "";

        let dictSize = 256;
        const dictionary = LZCompressor.buildInitialCompressDictionary();

        let w = "";
        const result: number[] = [];

        // Iterate characters and map recurring substrings to dictionary indices
        for (let i = 0; i < uncompressed.length; i++) {
            const c = uncompressed.charAt(i);
            const wc = w + c;

            if (dictionary.has(wc)) {
                w = wc;
            } else {
                result.push(dictionary.get(w)!);
                dictionary.set(wc, dictSize++);
                w = c;
            }

            // Periodically yield execution back to Script Engine to prevent watchdog crashes
            if (i > 0 && i % COMPRESSION_YIELD_THRESHOLD === 0) {
                await LZCompressor.yieldToEngine();
            }
        }

        if (w !== "") {
            result.push(dictionary.get(w)!);
        }

        return JSON.stringify(result);
    }

    /**
     * Decompresses an LZW-compressed payload string back to raw text/JSON.
     * @param compressed Compressed payload string generated by LZCompressor.
     * @returns Decompressed plain text string.
     */
    public static decompress(compressed: string): string {
        if (!compressed) return "";

        const compressedCodes = LZCompressor.parseCodes(compressed);
        if (!compressedCodes || compressedCodes.length === 0) return "";

        const dictionary = LZCompressor.buildInitialDecompressDictionary();
        let dictSize = 256;

        let w = String.fromCharCode(compressedCodes[0]!);
        let result = w;

        // Reconstruct string patterns sequentially from dictionary pointers
        for (let i = 1; i < compressedCodes.length; i++) {
            const k = compressedCodes[i];
            if (k === undefined) return "";

            const entry = LZCompressor.resolveEntry(k, dictSize, w, dictionary);
            if (!entry) return "";

            result += entry;
            dictionary.set(dictSize++, w + entry.charAt(0));
            w = entry;
        }

        return result;
    }

    /**
     * Yields execution to the server tick loop via system.run.
     */
    private static async yieldToEngine(): Promise<void> {
        return new Promise<void>((resolve) => system.run(resolve));
    }

    /**
     * Builds base ASCII character mapping table (0-255) for compression lookup.
     */
    private static buildInitialCompressDictionary(): Map<string, number> {
        const dictionary = new Map<string, number>();
        for (let i = 0; i < 256; i++) {
            dictionary.set(String.fromCharCode(i), i);
        }
        return dictionary;
    }

    /**
     * Builds base ASCII code mapping table (0-255) for decompression lookup.
     */
    private static buildInitialDecompressDictionary(): Map<number, string> {
        const dictionary = new Map<number, string>();
        for (let i = 0; i < 256; i++) {
            dictionary.set(i, String.fromCharCode(i));
        }
        return dictionary;
    }

    /**
     * Parses raw JSON string safely into numeric code sequence array.
     */
    private static parseCodes(compressed: string): number[] | undefined {
        try {
            const parsed = JSON.parse(compressed);
            return Array.isArray(parsed) ? parsed : undefined;
        } catch {
            return undefined;
        }
    }

    /**
     * Resolves target dictionary key during expansion.
     */
    private static resolveEntry(k: number, dictSize: number, w: string, dictionary: Map<number, string>): string | undefined {
        if (dictionary.has(k)) return dictionary.get(k)!;
        if (k === dictSize) return w + w.charAt(0);
        return undefined;
    }
}

/**
 * High-performance Dynamic Property database supporting compression,
 * automatic chunking, re-entrant locking, and batched cleanup operations.
 */
export class OptimizedDatabase<T extends Record<string, DatabaseValueObject>> {
    /** Target database unique namespace name */
    public name: string;

    /** Dynamic property key housing global pointer array index */
    private pointerKey: string;

    /** In-memory cached active key pointers */
    private cachedPointers: Set<string> | undefined = undefined;

    /** Indicates if delayed pointer write-back tick is already queued */
    private indexSaveScheduled = false;

    /** Global registry of instantiated active database references */
    private static instances: OptimizedDatabase<any>[] = [];

    /** Global mutual-exclusion re-entrant lock registry mapping resource keys to lock contexts */
    private static _locks = new Map<string, string>();

    /**
     * Constructs a new OptimizedDatabase instance.
     * @param name Name identifier for the database instance.
     */
    constructor(name: string) {
        if (!name || name.length === 0) throw new Error("[Paradox] Database name cannot be empty.");
        if (name.includes('"') || name.includes("/")) throw new Error('[Paradox] Database name cannot include `"` or `/`.');

        this.name = name;
        this.pointerKey = `${this.name}/pointers`;

        this.initializePointers();

        if (!OptimizedDatabase.instances.includes(this)) OptimizedDatabase.instances.push(this);
    }

    /**
     * Verifies index dynamic property structure initialized on storage layer.
     */
    private initializePointers(): void {
        try {
            if (world.getDynamicProperty(`${this.pointerKey}/0`) === undefined && world.getDynamicProperty(this.pointerKey) === undefined) {
                world.setDynamicProperty(`${this.pointerKey}/0`, JSON.stringify([]));
            }
        } catch {
            // Deferred load during world startup tick state
        }
    }

    /**
     * Retrieves all active database instances registered in runtime context.
     */
    public static getAllInstances(): OptimizedDatabase<any>[] {
        return this.instances;
    }

    /**
     * Reads pointer index keys into memory cache.
     */
    private _getPointers(): Set<string> {
        if (this.cachedPointers !== undefined) return this.cachedPointers;

        const chunks = this._readRawChunks(this.pointerKey);
        if (chunks.length === 0) return this._readLegacyPointers();

        try {
            const joined = chunks.join("");
            const parsed = joined.trim() ? JSON.parse(joined) : [];
            this.cachedPointers = new Set<string>(parsed);
        } catch {
            this.cachedPointers = new Set<string>();
        }

        return this.cachedPointers;
    }

    /**
     * Fallback strategy reading pre-chunking v1 database pointer strings.
     */
    private _readLegacyPointers(): Set<string> {
        try {
            const legacy = world.getDynamicProperty(this.pointerKey) as string | undefined;
            const parsed = legacy ? JSON.parse(legacy) : [];
            this.cachedPointers = new Set<string>(parsed);
        } catch {
            this.cachedPointers = new Set<string>();
        }
        return this.cachedPointers;
    }

    /**
     * Schedules or forces pointer index cache serialization to disk storage.
     * @param immediate If true, flushes index to storage immediately instead of scheduling next tick.
     */
    private _savePointers(immediate = false): void {
        if (!this.cachedPointers) return;

        if (immediate) {
            this._flushPointersToStorage();
            return;
        }

        if (this.indexSaveScheduled) return;
        this.indexSaveScheduled = true;

        // Schedule async write batching to unify rapid operations
        system.run(() => {
            this.indexSaveScheduled = false;
            this._flushPointersToStorage();
        });
    }

    /**
     * Serializes memory pointer cache and writes chunked segments to storage layer.
     */
    private _flushPointersToStorage(): void {
        if (!this.cachedPointers) return;

        const json = JSON.stringify(Array.from(this.cachedPointers));
        const chunks: Record<string, string> = {};

        let chunkIdx = 0;
        for (let i = 0; i < json.length; i += CHUNK_SIZE) {
            chunks[`${this.pointerKey}/${chunkIdx}`] = json.slice(i, i + CHUNK_SIZE);
            chunkIdx++;
        }

        this._cleanupExcessChunks(this.pointerKey, chunkIdx);
        world.setDynamicProperties(chunks);
    }

    /**
     * Executes function inside re-entrant lock guard targeting requested key resources.
     * @param resources Keys/Namespaces requiring mutex protection.
     * @param lockId Unique lock owner ID.
     * @param fn Task block executing under lock protection.
     */
    private static async _withLock<T>(resources: string[], lockId: string, fn: () => T | Promise<T>): Promise<T> {
        const TIMEOUT = 10000;
        const start = Date.now();

        // Spin-wait until resources clear block state
        while (OptimizedDatabase.isResourceBlocked(resources, lockId)) {
            if (Date.now() - start > TIMEOUT) throw new Error(`Lock timeout for resources: ${resources.join(", ")}`);
            await new Promise<void>((resolve) => system.run(resolve));
        }

        const acquired = OptimizedDatabase.acquireLocks(resources, lockId);

        try {
            return await fn();
        } finally {
            OptimizedDatabase.releaseLocks(acquired);
        }
    }

    /**
     * Evaluates if any requested resources are currently acquired by another caller context.
     */
    private static isResourceBlocked(resources: string[], lockId: string): boolean {
        return resources.some((res) => this._locks.has(res) && this._locks.get(res) !== lockId);
    }

    /**
     * Grants locks on requested resources for caller identity.
     */
    private static acquireLocks(resources: string[], lockId: string): string[] {
        const acquired: string[] = [];
        resources.forEach((res) => {
            if (!this._locks.has(res)) {
                this._locks.set(res, lockId);
                acquired.push(res);
            }
        });
        return acquired;
    }

    /**
     * Releases locks previously acquired by caller.
     */
    private static releaseLocks(acquired: string[]): void {
        acquired.forEach((res) => this._locks.delete(res));
    }

    /**
     * Generates context lock identity token string.
     */
    private _createLockContext(): string {
        return `${this.name}_${Date.now()}_${Math.random().toString(36).slice(2, 9)}`;
    }

    /**
     * Purges base key dynamic properties along with trailing chunk indices.
     */
    private _deleteChunks(baseKey: string): void {
        let i = 0;
        let consecutiveUndefined = 0;

        // Iterate forward clearing sequential indices until reaching double undefined boundary
        while (consecutiveUndefined < 3) {
            const key = `${baseKey}/${i}`;
            if (world.getDynamicProperty(key) !== undefined) {
                world.setDynamicProperty(key, undefined);
                consecutiveUndefined = 0;
            } else {
                consecutiveUndefined++;
            }
            i++;
        }
        world.setDynamicProperty(baseKey, undefined);
    }

    /**
     * Sweeps up legacy chunks remaining beyond updated shorter chunk boundary index.
     */
    private _cleanupExcessChunks(baseKey: string, startIndex: number): void {
        let i = startIndex;
        let consecutiveUndefined = 0;

        while (consecutiveUndefined < 3) {
            const key = `${baseKey}/${i}`;
            if (world.getDynamicProperty(key) !== undefined) {
                world.setDynamicProperty(key, undefined);
                consecutiveUndefined = 0;
            } else {
                consecutiveUndefined++;
            }
            i++;
        }
    }

    /**
     * Iterates sequential chunk paths returning raw dynamic property array data.
     */
    private _readRawChunks(baseKey: string): string[] {
        const chunks: string[] = [];
        for (let i = 0; ; ++i) {
            const c = world.getDynamicProperty(`${baseKey}/${i}`) as string | undefined;
            if (c === undefined) break;
            chunks.push(c);
        }
        return chunks;
    }

    /**
     * Stores an entry in the database, automatically compressing and splitting payloads across dynamic property chunks.
     * @param key Target database entry key.
     * @param value Structured object value payload.
     * @param lockId Optional lock owner identifier for context re-entrancy.
     */
    public async set<K extends keyof T>(key: K, value: T[K], lockId?: string): Promise<void> {
        const base = `${this.name}/${String(key)}`;
        const lockKeys = [this.name, base];
        const ctx = lockId ?? this._createLockContext();

        await OptimizedDatabase._withLock(lockKeys, ctx, async () => {
            const json = JSON.stringify(value);
            const rawCompressed = await LZCompressor.compress(json);

            // Fallback to uncompressed string if LZW expansion exceeds original length
            const payloadToStore = rawCompressed.length < json.length ? this._formatPayload(rawCompressed) : json;

            const updateBatch: Record<string, string> = {};

            let chunkIdx = 0;
            for (let i = 0; i < payloadToStore.length; i += CHUNK_SIZE) {
                updateBatch[`${base}/${chunkIdx}`] = payloadToStore.slice(i, i + CHUNK_SIZE);
                chunkIdx++;
            }

            this._cleanupExcessChunks(base, chunkIdx);
            world.setDynamicProperties(updateBatch);
        });

        this._updatePointerIndex(base);
    }

    /**
     * Inserts new pointer reference into active tracking index.
     */
    private _updatePointerIndex(base: string): void {
        const pointers = this._getPointers();
        if (!pointers.has(base)) {
            pointers.add(base);
            this._savePointers();
        }
    }

    /**
     * Formats compressed binary string with metadata header tracking total expected chunks.
     */
    private _formatPayload(rawCompressed: string): string {
        const dummyHeader = "\u0002:0:";
        let chunkCount = Math.ceil((dummyHeader.length + rawCompressed.length) / CHUNK_SIZE);
        let payload = `\u0002:${chunkCount}:` + rawCompressed;

        if (payload.length > chunkCount * CHUNK_SIZE) {
            chunkCount = Math.ceil(payload.length / CHUNK_SIZE);
            payload = `\u0002:${chunkCount}:` + rawCompressed;
        }
        return payload;
    }

    /**
     * Retrieves an entry from the database, resolving multi-chunk payloads and performing decompression.
     * @param key Target key to look up.
     * @param lockId Optional lock owner identifier for context re-entrancy.
     * @returns Parsed value payload or undefined if non-existent or corrupted.
     */
    public async get<K extends keyof T>(key: K, lockId?: string): Promise<T[K] | undefined> {
        const base = `${this.name}/${String(key)}`;
        const lockKeys = [this.name, base];
        const ctx = lockId ?? this._createLockContext();

        return await OptimizedDatabase._withLock(lockKeys, ctx, async () => {
            const chunks = this._readRawChunks(base);
            if (!chunks.length) return undefined;

            const rawData = chunks.join("").trim();
            if (!rawData) return undefined;

            return this._parseEntryData(rawData, chunks.length, String(key));
        });
    }

    /**
     * Inspects raw data string and routes to appropriate decompression parser or raw JSON reader.
     */
    private _parseEntryData(rawData: string, chunkCount: number, keyStr: string): any {
        try {
            if (rawData.startsWith("\u0002")) {
                return this._parseCompressedHeader(rawData, chunkCount, keyStr);
            }
            return JSON.parse(rawData);
        } catch (err) {
            console.warn(`[${this.name}] Failed to parse entry for key "${keyStr}":`, err);
            return undefined;
        }
    }

    /**
     * Validates expected chunk count metadata and executes LZW payload decompression.
     */
    private _parseCompressedHeader(rawData: string, chunkCount: number, keyStr: string): any {
        const headerEnd = rawData.indexOf(":", 2);
        if (headerEnd === -1) return undefined;

        const expectedChunks = parseInt(rawData.slice(2, headerEnd), 10);
        if (!isNaN(expectedChunks) && chunkCount < expectedChunks) {
            console.warn(`[${this.name}] Corrupted entry for key "${keyStr}": expected ${expectedChunks} chunks, found ${chunkCount}`);
            return undefined;
        }

        const decompressed = LZCompressor.decompress(rawData.slice(headerEnd + 1));
        return decompressed.trim() ? JSON.parse(decompressed) : undefined;
    }

    /**
     * Migrates legacy uncompressed dynamic property entries to v2 chunked/compressed format.
     * @returns Migration metric object summarizing converted entry counts and space savings.
     */
    public async migrateToV2(): Promise<{ migrated: number; originalBytes: number; compressedBytes: number }> {
        let migratedCount = 0;
        let originalTotal = 0;
        let compressedTotal = 0;

        const ctx = this._createLockContext();
        const pointers = this._getPointers();

        for (const ptr of pointers) {
            const key = ptr.split("/").pop() as keyof T;
            const chunks = this._readRawChunks(ptr);
            const rawData = chunks.join("");

            if (!rawData.startsWith("\u0002") && rawData.length > 0) {
                const parsedValue = await this.get(key, ctx);
                if (parsedValue !== undefined) {
                    const beforeBytes = this.getEntrySizeBytes(String(key));
                    await this.set(key, parsedValue, ctx);
                    const afterBytes = this.getEntrySizeBytes(String(key));

                    originalTotal += beforeBytes;
                    compressedTotal += afterBytes;
                    migratedCount++;
                }
            }
        }

        return { migrated: migratedCount, originalBytes: originalTotal, compressedBytes: compressedTotal };
    }

    /**
     * Removes a specific entry by key and purges chunk references.
     * @param key Target database entry key.
     * @param lockId Optional lock owner identifier for context re-entrancy.
     */
    public async delete<K extends keyof T>(key: K, lockId?: string): Promise<void> {
        const base = `${this.name}/${String(key)}`;
        const lockKeys = [this.name, base];
        const ctx = lockId ?? this._createLockContext();

        await OptimizedDatabase._withLock(lockKeys, ctx, async () => {
            this._deleteChunks(base);
            const pointers = this._getPointers();
            if (pointers.delete(base)) {
                this._savePointers();
            }
        });
    }

    /**
     * Clears all stored entries, resets pointer index, and purges physical chunk storage.
     */
    public async clear(): Promise<void> {
        const ctx = this._createLockContext();

        await OptimizedDatabase._withLock([this.name], ctx, async () => {
            const pointers = this._getPointers();
            pointers.forEach((ptr) => this._deleteChunks(ptr));
            this.cachedPointers = new Set<string>();
            this._savePointers(true);
        });
    }

    /**
     * Returns key-value pairs stored in the database instance.
     * @param lockId Optional lock owner identifier for context re-entrancy.
     * @returns Array containing key-value tuple arrays.
     */
    public async entries(lockId?: string): Promise<[keyof T, T[keyof T]][]> {
        const pointers = this._getPointers();
        const result: [keyof T, T[keyof T]][] = [];
        const ctx = lockId ?? this._createLockContext();

        for (const ptr of pointers) {
            const key = ptr.split("/").pop() as keyof T;
            const value = await this.get(key, ctx);
            if (value !== undefined) {
                result.push([key, value]);
            }
        }

        return result;
    }

    /**
     * Evaluates default validity rules for automatic entry pruning sweeps.
     */
    private isDefaultValid(value: any): boolean {
        if (value === undefined) return false;
        if (typeof value === "string" && value.trim() === "") return false;
        if (Array.isArray(value) && value.length === 0) return false;
        if (typeof value === "object" && !Array.isArray(value) && Object.keys(value).length === 0) return false;
        if (typeof value === "number" && isNaN(value)) return false;
        return typeof value !== "function" && typeof value !== "symbol";
    }

    /**
     * Evaluates database entries against a predicate in batch promises and purges invalid keys.
     * @param validator Optional custom evaluation callback function.
     * @param options Execution configuration controlling log suppression.
     */
    public async clean(validator?: (key: keyof T, value: T[keyof T]) => boolean, options?: { silent?: boolean }): Promise<void> {
        const silent = options?.silent ?? false;
        const ctx = this._createLockContext();

        await OptimizedDatabase._withLock([this.name], ctx, async () => {
            const pointers = Array.from(this._getPointers());
            let deletedCount = 0;

            for (let i = 0; i < pointers.length; i += CLEANUP_BATCH_SIZE) {
                const batch = pointers.slice(i, i + CLEANUP_BATCH_SIZE);

                // Fetch and evaluate batch concurrently to minimize await starvation
                const evaluatedBatch = await Promise.all(
                    batch.map(async (ptr) => {
                        const key = ptr.split("/").pop() as keyof T;
                        const value = await this.get(key, ctx);
                        const isValid = validator ? validator(key, value as T[keyof T]) : this.isDefaultValid(value);
                        return { ptr, key, value, isValid };
                    })
                );

                for (const item of evaluatedBatch) {
                    if (!item.isValid) {
                        this._deleteChunks(item.ptr);
                        this._getPointers().delete(item.ptr);
                        if (!silent) console.warn(`[${this.name}] Deleted invalid entry "${String(item.key)}" with value:`, item.value);
                        deletedCount++;
                    }
                }
            }

            if (deletedCount > 0) {
                this._savePointers(true);
            }

            if (!silent) console.log(`[${this.name}] Cleanup complete. Total deleted entries: ${deletedCount}`);
        });
    }

    /**
     * Lists active registered storage entry pointer key strings.
     */
    public listPointers(): string[] {
        return Array.from(this._getPointers());
    }

    /**
     * Computes storage footprint in bytes for given key entry.
     * @param key Target database key.
     */
    public getEntrySizeBytes(key: string): number {
        const base = `${this.name}/${key}`;
        let bytes = 0;
        for (let i = 0; ; i++) {
            const chunk = world.getDynamicProperty(`${base}/${i}`) as string | undefined;
            if (chunk === undefined) break;
            bytes += chunk.length * 2; // UTF-16 character byte size calculation
        }
        return bytes;
    }

    /**
     * Formats numeric byte sizes into human-readable string units.
     * @param bytes Numeric raw byte total.
     */
    public formatBytes(bytes: number): string {
        const sizes = ["B", "KB", "MB", "GB", "TB"];
        if (bytes <= 0) return "0 B";
        const i = Math.min(Math.floor(Math.log(bytes) / Math.log(1024)), sizes.length - 1);
        const value = bytes / Math.pow(1024, i);
        return `${value.toFixed(2)} ${sizes[i]}`;
    }

    /**
     * Calculates combined storage consumption across all keys.
     */
    public getTotalSizeFormatted(): string {
        let totalBytes = 0;
        for (const ptr of this._getPointers()) {
            const key = ptr.split("/").pop()!;
            totalBytes += this.getEntrySizeBytes(key);
        }
        return this.formatBytes(totalBytes);
    }

    /**
     * Counts physical chunks allocated for key.
     * @param key Target database key.
     */
    public getChunkCount(key: string): number {
        const base = `${this.name}/${key}`;
        let count = 0;
        while (world.getDynamicProperty(`${base}/${count}`) !== undefined) count++;
        return count;
    }

    /**
     * Checks if key reference exists inside active index pointer cache.
     * @param key Target database key.
     */
    public containsKey(key: string): boolean {
        return this._getPointers().has(`${this.name}/${key}`);
    }
}
