export const verses = [
    // Old Testament
    "Genesis 1:1 — In the beginning, God created the heavens and the earth.",
    "Genesis 50:20 — You meant evil against me, but God meant it for good.",
    "Exodus 14:14 — The Lord will fight for you; you need only to be still.",
    "Exodus 33:14 — My presence will go with you, and I will give you rest.",
    "Numbers 6:24 — The Lord bless you and keep you.",
    "Deuteronomy 31:8 — The Lord himself goes before you and will be with you.",
    "Joshua 1:9 — Be strong and courageous. Do not be frightened.",
    "Judges 5:31 — Let those who love him be like the sun.",
    "Ruth 2:12 — May the Lord repay you for what you have done.",
    "1 Samuel 12:24 — Fear the Lord and serve him faithfully.",
    "1 Samuel 16:7 — The Lord sees not as man sees.",
    "2 Samuel 22:2 — The Lord is my rock and my fortress.",
    "2 Samuel 22:31 — The Word of the Lord is proven.",
    "1 Kings 8:56 — Blessed be the Lord who has given rest.",
    "2 Kings 20:5 — I have heard your prayer.",
    "1 Chronicles 16:11 — Seek the Lord and his strength.",
    "2 Chronicles 16:9 — The eyes of the Lord range throughout the earth.",
    "Ezra 10:4 — Arise, for it is your task.",
    "Nehemiah 8:10 — The joy of the Lord is your strength.",
    "Job 19:25 — I know that my Redeemer lives.",
    "Psalm 23:1 — The Lord is my shepherd; I shall not want.",
    "Psalm 27:1 — The Lord is my light and my salvation.",
    "Psalm 34:8 — Oh, taste and see that the Lord is good.",
    "Psalm 37:4 — Delight yourself in the Lord, and he will give you the desires of your heart.",
    "Psalm 46:1 — God is our refuge and strength, a very present help in trouble.",
    "Psalm 55:22 — Cast your burden on the Lord.",
    "Psalm 91:1 — He who dwells in the shelter of the Most High will abide in the shadow of the Almighty.",
    "Psalm 118:24 — This is the day that the Lord has made; let us rejoice and be glad in it.",
    "Psalm 119:11 — I have stored up your word in my heart.",
    "Psalm 121:1-2 — I lift up my eyes to the hills. From where does my help come? My help comes from the Lord.",
    "Proverbs 3:5 — Trust in the Lord with all your heart.",
    "Proverbs 3:6 — In all your ways acknowledge him, and he will make straight your paths.",
    "Proverbs 4:23 — Keep your heart with all vigilance, for from it flow the springs of life.",
    "Proverbs 16:3 — Commit your work to the Lord.",
    "Proverbs 18:10 — The name of the Lord is a strong tower; the righteous run to it and are safe.",
    "Ecclesiastes 3:11 — He has made everything beautiful in its time.",
    "Song of Solomon 8:7 — Many waters cannot quench love.",
    "Isaiah 12:2 — Behold, God is my salvation; I will trust and not be afraid.",
    "Isaiah 26:3 — You keep him in perfect peace whose mind is stayed on you.",
    "Isaiah 40:31 — But they who wait for the Lord shall renew their strength.",
    "Isaiah 41:10 — Fear not, for I am with you.",
    "Isaiah 43:2 — When you pass through the waters, I will be with you.",
    "Jeremiah 17:7 — Blessed is the man who trusts in the Lord.",
    "Jeremiah 29:11 — For I know the plans I have for you.",
    "Jeremiah 33:3 — Call to me and I will answer you.",
    "Lamentations 3:22 — The steadfast love of the Lord never ceases.",
    "Ezekiel 36:26 — I will give you a new heart.",
    "Ezekiel 37:14 — I will put my Spirit within you, and you shall live.",
    "Daniel 3:17 — Our God whom we serve is able to deliver us.",
    "Daniel 6:23 — No harm was found on him because he trusted in his God.",
    "Hosea 6:6 — For I desire steadfast love, not sacrifice.",
    "Joel 2:28 — I will pour out my Spirit on all flesh.",
    "Amos 5:24 — Let justice roll down like waters.",
    "Obadiah 1:15 — The day of the Lord is near for all nations.",
    "Jonah 2:2 — I called out to the Lord, and he answered me.",
    "Micah 6:8 — Walk humbly with your God.",
    "Nahum 1:7 — The Lord is good, a stronghold in the day of trouble.",
    "Zephaniah 3:17 — The Lord your God is in your midst.",
    "Haggai 2:4 — Be strong, all you people of the land, and work, for I am with you, declares the Lord.",
    "Malachi 3:10 — Bring the full tithe into the storehouse.",
    "Malachi 4:2 — The sun of righteousness shall rise with healing in its wings.",

    // New Testament
    "Matthew 5:14 — You are the light of the world.",
    "Matthew 6:33 — Seek first the kingdom of God.",
    "Matthew 11:28 — Come to me, all who labor and are heavy laden.",
    "Matthew 28:20 — I am with you always, to the end of the age.",
    "Mark 9:23 — All things are possible for one who believes.",
    "Mark 10:27 — With God all things are possible.",
    "Luke 1:37 — Nothing will be impossible with God.",
    "Luke 6:36 — Be merciful, even as your Father is merciful.",
    "Luke 18:27 — What is impossible with man is possible with God.",
    "John 3:16 — For God so loved the world...",
    "John 8:12 — I am the light of the world.",
    "John 14:27 — Peace I leave with you; my peace I give to you.",
    "John 15:13 — Greater love has no one than this.",
    "Acts 1:8 — You will receive power when the Holy Spirit comes upon you.",
    "Acts 4:12 — There is salvation in no one else.",
    "Romans 5:8 — God shows his love for us in that while we were sinners, Christ died for us.",
    "Romans 8:28 — All things work together for good.",
    "Romans 8:31 — If God is for us, who can be against us?",
    "Romans 8:38-39 — Nothing can separate us from the love of God.",
    "Romans 12:12 — Rejoice in hope, be patient in tribulation.",
    "Romans 15:13 — May the God of hope fill you with all joy and peace.",
    "1 Corinthians 10:13 — God is faithful; he will not let you be tempted beyond your ability.",
    "1 Corinthians 13:4 — Love is patient and kind...",
    "1 Corinthians 16:14 — Let all that you do be done in love.",
    "2 Corinthians 4:18 — We look not to the things that are seen but to the things that are unseen.",
    "2 Corinthians 5:7 — We walk by faith, not by sight.",
    "2 Corinthians 9:7 — God loves a cheerful giver.",
    "2 Corinthians 12:9 — My grace is sufficient for you.",
    "Galatians 2:20 — I have been crucified with Christ; it is no longer I who live.",
    "Galatians 5:22 — The fruit of the Spirit is love, joy, peace...",
    "Galatians 6:9 — Let us not grow weary of doing good.",
    "Ephesians 2:8 — By grace you have been saved through faith.",
    "Ephesians 3:20 — Now to him who is able to do far more abundantly.",
    "Ephesians 6:10 — Be strong in the Lord and in his mighty power.",
    "Philippians 2:3 — In humility count others more significant than yourselves.",
    "Philippians 4:6 — Do not be anxious about anything.",
    "Philippians 4:13 — I can do all things through Christ...",
    "Colossians 3:2 — Set your minds on things above.",
    "Colossians 3:15 — Let the peace of Christ rule in your hearts.",
    "1 Thessalonians 4:16 — The Lord will descend from heaven with a cry of command.",
    "1 Thessalonians 5:16 — Rejoice always.",
    "1 Thessalonians 5:24 — He who calls you is faithful; he will surely do it.",
    "2 Thessalonians 3:3 — The Lord is faithful.",
    "1 Timothy 4:12 — Set the believers an example.",
    "2 Timothy 1:7 — For God gave us a spirit not of fear.",
    "2 Timothy 2:13 — If we are faithless, he remains faithful.",
    "2 Timothy 3:16 — All Scripture is breathed out by God and profitable for teaching.",
    "Titus 2:11 — For the grace of God has appeared.",
    "Philemon 1:7 — Your love has refreshed the hearts of the saints.",
    "Hebrews 4:16 — Let us then with confidence draw near to the throne of grace.",
    "Hebrews 10:23 — Let us hold fast the confession of our hope.",
    "Hebrews 11:1 — Now faith is the assurance of things hoped for.",
    "Hebrews 12:2 — Fix your eyes on Jesus, the founder and perfecter of our faith.",
    "Hebrews 13:5 — I will never leave you nor forsake you.",
    "James 1:5 — If any lacks wisdom, let him ask God.",
    "James 1:12 — Blessed is the man who remains steadfast under trial.",
    "James 4:8 — Draw near to God, and he will draw near to you.",
    "1 Peter 2:9 — You are a chosen race, a royal priesthood.",
    "1 Peter 3:15 — Always be ready to give a defense for your hope.",
    "1 Peter 5:7 — Cast all your anxieties on him.",
    "2 Peter 1:3 — His divine power has granted to us all things.",
    "2 Peter 3:9 — The Lord is patient toward you.",
    "1 John 1:9 — If we confess our sins, he is faithful and just to forgive us.",
    "1 John 3:18 — Let us love not in word or talk but in deed and in truth.",
    "1 John 5:14 — If we ask anything according to his will, he hears us.",
    "2 John 1:6 — Walk in love.",
    "3 John 1:2 — I pray that all may go well with you.",
    "Jude 1:24 — To him who is able to keep you from falling.",
    "Revelation 3:20 — Behold, I stand at the door and knock.",
    "Revelation 21:4 — He will wipe away every tear from their eyes.",
    "Revelation 22:13 — I am the Alpha and the Omega, the first and the last, the beginning and the end.",
];
